#!/bin/sh
set -e

pcs property set no-quorum-policy=ignore
pcs property set stonith-enabled=false
pcs resource rsc defaults resource-stickiness=INFINITY migration-threshold=1
pcs resource create iptables lsb:iptables op monitor interval="5s"
pcs resource create associate-routing lsb:associate-routing

exit 0
