#!/bin/sh
#
# chkconfig: 2345 99 10
# description: Associate EIP

# Source Function Library
. /etc/init.d/functions

# System Variable
prog=${0##*/}
lock=/var/lock/subsys/$prog

# User Variavle
PRIVATE_IP=0.0.0.0

# Source Config
if [ -f /etc/sysconfig/$prog ] ; then
    . /etc/sysconfig/$prog
fi

#
case "$1" in
    start)
        touch $lock
        AZ=`curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone`
        REGION=`echo $AZ | cut -c 1-$((${#AZ} - 1))`
        MAC=`curl -s http://169.254.169.254/latest/meta-data/mac`
        INTERFACE_ID=`curl -s http://169.254.169.254/latest/meta-data/network/interfaces/macs/$MAC/interface-id`
        aws --region $REGION ec2 assign-private-ip-addresses \
        --network-interface-id $INTERFACE_ID \
        --private-ip-addresses $PRIVATE_IP \
        --allow-reassignment \
        | logger -s -i -t $prog
        exit ${PIPESTATUS[0]}
        ;;
    stop)
        rm -f $lock
        exit 0
        ;;
    status)
        if [ -f $lock ] ; then
            exit 0
        else
            exit 3
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
esac
